=== ciroRubiales95/lenguajesMarcas04/biblioteca.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT biblioteca (libro*)>
<!ELEMENT libro (codigo, titulo, editorial, edicion?, ISBM, paginas?, autor+, formato+)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT edicion (#PCDATA)>
<!ELEMENT ISBM (#PCDATA)>
<!ELEMENT paginas (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT formato (#PCDATA)>


<!ATTLIST autor pais CDATA #REQUIRED>

=== ciroRubiales95/lenguajesMarcas04/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- <!DOCTYPE biblioteca SYSTEM "biblioteca.dtd"> -->
<?xml-model href="biblioteca.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<biblioteca 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="biblioteca.xsd">
    <libro>
        <codigo>454641</codigo>
        <titulo>1984</titulo>
        <editorial>publicamos</editorial>
        <edicion>4</edicion>
        <ISBM>9788499890944</ISBM>
        <paginas>352</paginas>
        <autor>George Orwell</autor>
        <formato>digital</formato>
    </libro>
    <libro>
        <codigo>456481</codigo>
        <titulo>Pedro Páramo</titulo>
        <editorial>editamos</editorial>
        <edicion>5</edicion>
        <ISBM>97884934426</ISBM>
        <paginas>136</paginas>
        <autor>Juan Rulfo</autor>
        <formato>papel</formato>
    </libro>
    <libro>
        <codigo>5896111</codigo>
        <titulo>Las intermitencias de la muerte</titulo>
        <editorial>publicamos</editorial>
        <edicion>15</edicion>
        <ISBM>978849062877</ISBM>
        <paginas>256</paginas>
        <autor>José Saramago</autor>
        <formato>digital</formato>
    </libro>
</biblioteca>
